server:
  port: 8080
  # servlet：上下文路径，默认 / ，可以通过此方式设置上下文访问路径
  servlet:
    context-path: /ChatRoom_Server

spring:
  datasource:
    name: chatroom
    # 采用druid的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接数据库的url
    url: jdbc:mysql:///chatroom
    # 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 用户名
    username: root
    password: abc123
    # 监控统计
    filters: stat
    initial-size: 2 # 初始化连接
    max-idle: 10 # 最大空闲连接数
    min-idle: 1 # 最小空闲连接数
    max-active: 20 # 最大活动连接
    # 获取连接超时的等待时间
    max-wait: 60000
    # 间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-evict-runs-millis: 60000
    # 一个连接在池中最小生成的空间
    min-evictable-time-millis: 300000
    # 验证连接有效与否的SQL，不用的数据配置不同
    validation-query: SELECT 'x'
    # 指明连接是否被空闲连接回收器（如果有）进行连接，如果检测失败，则连接被冲池中去除
    test-while-idle: true
    # 借出连接时不要测试，否则影响性能
    test-on-borrow: false
  # springmvc 视图解析器前缀和后缀为指定名称的路径
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.56.5:22122